-- Create the projects table in public schema
CREATE TABLE IF NOT EXISTS public.projects (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    title TEXT NOT NULL,
    description TEXT NOT NULL,
    category TEXT NOT NULL,
    tags TEXT[] DEFAULT '{}',
    link TEXT,
    github TEXT,
    image TEXT,
    featured BOOLEAN DEFAULT false
);

-- Enable Row Level Security (RLS)
ALTER TABLE public.projects ENABLE ROW LEVEL SECURITY;

-- Create a policy to allow public read access
CREATE POLICY "Allow public read access" ON public.projects
    FOR SELECT
    TO anon
    USING (true);

-- Grant usage on schema and table to anon (just in case)
GRANT USAGE ON SCHEMA public TO anon;
GRANT SELECT ON public.projects TO anon;

-- Insert sample data (matching your previous hardcoded data)
INSERT INTO public.projects (title, description, category, tags, link, featured)
VALUES
    ('Smart Travel Planner', 'AI-powered travel agent that creates personalized itineraries based on user preferences and historical data.', 'AI Agent', ARRAY['Python', 'LangChain', 'OpenAI'], '#', true),
    ('E-Commerce Analytics', 'Advanced data analysis platform for e-commerce metrics with predictive sales modeling.', 'Data Analysis', ARRAY['Python', 'Pandas', 'Scikit-learn'], '#', true),
    ('Predictive Finance Tracker', 'Personal finance tool using machine learning to categorize transactions and forecast future expenses.', 'Machine Learning', ARRAY['TensorFlow', 'FastAPI', 'React'], '#', true),
    ('Customer Support Bot', 'Intelligent chatbot capable of handling complex customer queries and executing actions.', 'AI Agent', ARRAY['NLP', 'RAG', 'Vector DB'], '#', false),
    ('Market Trend Analyzer', 'Real-time market analysis tool processing millions of data points to identify emerging trends.', 'Data Analysis', ARRAY['Big Data', 'Spark', 'Visualization'], '#', false);
